package com.dream.common.vo.wms;

import java.io.Serializable;
import java.util.Date;

public class WmsFoodCalorie implements Serializable {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column wms_food_calorie.id
     *
     * @mbg.generated Fri Jan 28 14:48:45 CST 2022
     */
    private Long id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column wms_food_calorie.version
     *
     * @mbg.generated Fri Jan 28 14:48:45 CST 2022
     */
    private Integer version;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column wms_food_calorie.creator
     *
     * @mbg.generated Fri Jan 28 14:48:45 CST 2022
     */
    private String creator;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column wms_food_calorie.create_time
     *
     * @mbg.generated Fri Jan 28 14:48:45 CST 2022
     */
    private Date createTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column wms_food_calorie.updater
     *
     * @mbg.generated Fri Jan 28 14:48:45 CST 2022
     */
    private String updater;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column wms_food_calorie.update_time
     *
     * @mbg.generated Fri Jan 28 14:48:45 CST 2022
     */
    private Date updateTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column wms_food_calorie.food_name
     *
     * @mbg.generated Fri Jan 28 14:48:45 CST 2022
     */
    private String foodName;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column wms_food_calorie.food_calorie
     *
     * @mbg.generated Fri Jan 28 14:48:45 CST 2022
     */
    private Long foodCalorie;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column wms_food_calorie.food_picture
     *
     * @mbg.generated Fri Jan 28 14:48:45 CST 2022
     */
    private String foodPicture;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column wms_food_calorie.remark
     *
     * @mbg.generated Fri Jan 28 14:48:45 CST 2022
     */
    private String remark;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table wms_food_calorie
     *
     * @mbg.generated Fri Jan 28 14:48:45 CST 2022
     */
    private static final long serialVersionUID = 1L;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column wms_food_calorie.id
     *
     * @return the value of wms_food_calorie.id
     *
     * @mbg.generated Fri Jan 28 14:48:45 CST 2022
     */
    public Long getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column wms_food_calorie.id
     *
     * @param id the value for wms_food_calorie.id
     *
     * @mbg.generated Fri Jan 28 14:48:45 CST 2022
     */
    public void setId(Long id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column wms_food_calorie.version
     *
     * @return the value of wms_food_calorie.version
     *
     * @mbg.generated Fri Jan 28 14:48:45 CST 2022
     */
    public Integer getVersion() {
        return version;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column wms_food_calorie.version
     *
     * @param version the value for wms_food_calorie.version
     *
     * @mbg.generated Fri Jan 28 14:48:45 CST 2022
     */
    public void setVersion(Integer version) {
        this.version = version;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column wms_food_calorie.creator
     *
     * @return the value of wms_food_calorie.creator
     *
     * @mbg.generated Fri Jan 28 14:48:45 CST 2022
     */
    public String getCreator() {
        return creator;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column wms_food_calorie.creator
     *
     * @param creator the value for wms_food_calorie.creator
     *
     * @mbg.generated Fri Jan 28 14:48:45 CST 2022
     */
    public void setCreator(String creator) {
        this.creator = creator == null ? null : creator.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column wms_food_calorie.create_time
     *
     * @return the value of wms_food_calorie.create_time
     *
     * @mbg.generated Fri Jan 28 14:48:45 CST 2022
     */
    public Date getCreateTime() {
        return createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column wms_food_calorie.create_time
     *
     * @param createTime the value for wms_food_calorie.create_time
     *
     * @mbg.generated Fri Jan 28 14:48:45 CST 2022
     */
    public void setCreateTime(Date createTime) {
        this.createTime = createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column wms_food_calorie.updater
     *
     * @return the value of wms_food_calorie.updater
     *
     * @mbg.generated Fri Jan 28 14:48:45 CST 2022
     */
    public String getUpdater() {
        return updater;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column wms_food_calorie.updater
     *
     * @param updater the value for wms_food_calorie.updater
     *
     * @mbg.generated Fri Jan 28 14:48:45 CST 2022
     */
    public void setUpdater(String updater) {
        this.updater = updater == null ? null : updater.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column wms_food_calorie.update_time
     *
     * @return the value of wms_food_calorie.update_time
     *
     * @mbg.generated Fri Jan 28 14:48:45 CST 2022
     */
    public Date getUpdateTime() {
        return updateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column wms_food_calorie.update_time
     *
     * @param updateTime the value for wms_food_calorie.update_time
     *
     * @mbg.generated Fri Jan 28 14:48:45 CST 2022
     */
    public void setUpdateTime(Date updateTime) {
        this.updateTime = updateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column wms_food_calorie.food_name
     *
     * @return the value of wms_food_calorie.food_name
     *
     * @mbg.generated Fri Jan 28 14:48:45 CST 2022
     */
    public String getFoodName() {
        return foodName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column wms_food_calorie.food_name
     *
     * @param foodName the value for wms_food_calorie.food_name
     *
     * @mbg.generated Fri Jan 28 14:48:45 CST 2022
     */
    public void setFoodName(String foodName) {
        this.foodName = foodName == null ? null : foodName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column wms_food_calorie.food_calorie
     *
     * @return the value of wms_food_calorie.food_calorie
     *
     * @mbg.generated Fri Jan 28 14:48:45 CST 2022
     */
    public Long getFoodCalorie() {
        return foodCalorie;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column wms_food_calorie.food_calorie
     *
     * @param foodCalorie the value for wms_food_calorie.food_calorie
     *
     * @mbg.generated Fri Jan 28 14:48:45 CST 2022
     */
    public void setFoodCalorie(Long foodCalorie) {
        this.foodCalorie = foodCalorie;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column wms_food_calorie.food_picture
     *
     * @return the value of wms_food_calorie.food_picture
     *
     * @mbg.generated Fri Jan 28 14:48:45 CST 2022
     */
    public String getFoodPicture() {
        return foodPicture;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column wms_food_calorie.food_picture
     *
     * @param foodPicture the value for wms_food_calorie.food_picture
     *
     * @mbg.generated Fri Jan 28 14:48:45 CST 2022
     */
    public void setFoodPicture(String foodPicture) {
        this.foodPicture = foodPicture == null ? null : foodPicture.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column wms_food_calorie.remark
     *
     * @return the value of wms_food_calorie.remark
     *
     * @mbg.generated Fri Jan 28 14:48:45 CST 2022
     */
    public String getRemark() {
        return remark;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column wms_food_calorie.remark
     *
     * @param remark the value for wms_food_calorie.remark
     *
     * @mbg.generated Fri Jan 28 14:48:45 CST 2022
     */
    public void setRemark(String remark) {
        this.remark = remark == null ? null : remark.trim();
    }
}