package com.dream.common.mapper.wms;

import com.dream.common.vo.wms.WmsFoodCalorie;
import com.dream.common.vo.wms.WmsFoodCalorieExample;
import org.apache.ibatis.annotations.Param;

import java.util.List;
import java.util.Map;

public interface foodCalorieMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table wms_food_calorie
     *
     * @mbg.generated Fri Jan 28 14:48:45 CST 2022
     */
    List<WmsFoodCalorie> queryFoodCalorie(Map map);



}