package com.dream.common.mapper.wms;

import com.dream.common.vo.wms.WmsFoodCalorie;
import com.dream.common.vo.wms.WmsFoodCalorieExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface WmsFoodCalorieMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table wms_food_calorie
     *
     * @mbg.generated Fri Jan 28 14:48:45 CST 2022
     */
    long countByExample(WmsFoodCalorieExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table wms_food_calorie
     *
     * @mbg.generated Fri Jan 28 14:48:45 CST 2022
     */
    int deleteByExample(WmsFoodCalorieExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table wms_food_calorie
     *
     * @mbg.generated Fri Jan 28 14:48:45 CST 2022
     */
    int deleteByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table wms_food_calorie
     *
     * @mbg.generated Fri Jan 28 14:48:45 CST 2022
     */
    int insert(WmsFoodCalorie record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table wms_food_calorie
     *
     * @mbg.generated Fri Jan 28 14:48:45 CST 2022
     */
    int insertSelective(WmsFoodCalorie record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table wms_food_calorie
     *
     * @mbg.generated Fri Jan 28 14:48:45 CST 2022
     */
    List<WmsFoodCalorie> selectByExample(WmsFoodCalorieExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table wms_food_calorie
     *
     * @mbg.generated Fri Jan 28 14:48:45 CST 2022
     */
    WmsFoodCalorie selectByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table wms_food_calorie
     *
     * @mbg.generated Fri Jan 28 14:48:45 CST 2022
     */
    int updateByExampleSelective(@Param("record") WmsFoodCalorie record, @Param("example") WmsFoodCalorieExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table wms_food_calorie
     *
     * @mbg.generated Fri Jan 28 14:48:45 CST 2022
     */
    int updateByExample(@Param("record") WmsFoodCalorie record, @Param("example") WmsFoodCalorieExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table wms_food_calorie
     *
     * @mbg.generated Fri Jan 28 14:48:45 CST 2022
     */
    int updateByPrimaryKeySelective(WmsFoodCalorie record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table wms_food_calorie
     *
     * @mbg.generated Fri Jan 28 14:48:45 CST 2022
     */
    int updateByPrimaryKey(WmsFoodCalorie record);
}